### PR TITLE
Some fixes (see commits)

### PR DESCRIPTION
**Pull request by jonpetri**
Hi,
I find this implementation of `future::then()` very interesting (and also the only one I could find).
I found some issues while trying it. Here are the fixes, even if the project looks asleep,

### CODE REVIEW

**Comment by jaredhoberock** [comment]
Thanks for these changes. Just out of curiosity, what's your interest in this?

**Comment by jonpetri** [comment]
@jaredhoberock  
The future / then pattern makes an asynchronous API easier to read ans easier to use.

Let say we need  function  with async return: "doSomething". We could implement it with something a bit complex like a callback, or a signal. With the future/then pattern, everything is kept in one function: `future<ResultType> doSomething()`. Furthermore, with this, no need of any comment, everything is in there: the fact that the return is async, the result type.

The usage is also easy to read. The function call and the async continuation are packed together:
```
    doSomething().then(
        [&xx](auto result)
        {
            const auto ret = result.get();
            ...
        });
```

**Comment by jonpetri** [comment]
But let me ask something too. I couldn't find an "official" implementation of this:
https://en.cppreference.com/w/cpp/experimental/future/then

Do you know why? or where to find it?

**Comment by jaredhoberock** [comment]
Thanks for the explanation. I agree. The C++ Standards Committee decided to move in a direction away from futures, so `.then` was never standardized.

You might be able to find alternative takes on an implementation in other codebases like HPX.

**Pull request merged**
